version: '3.8'

services:
  scraper:
    build: .
    ports:
      - '8000:8000'
    restart: always
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=isit_db
      - DB_USER=postgres
      - DB_PASSWORD=Kirill2305

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: isit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kirill2305
    ports:
      - "5432:5432"